### ISSUE TITLE
Failing builds on circleci

### ISSUE THREAD

**Issue by JensRavens** [gidztech/jest-puppeteer-docker#20]
I really like your projects and the idea of just putting chrome into docker instead of the whole test stack really makes my tests a lot faster (from about 4.5min down to 50s on my mac compared to just using jest-puppeteer). Now I'd like to run the same tests in CircleCI but I'm running into some issues:

```
Building chromium

Docker Chromium: Successfully built Docker image
Docker Chromium: Starting Docker container...

Creating network "docker_default" with the default driver
Creating docker_chromium_1 ... 


Docker Chromium: Successfully started Docker container
Docker Chromium: Contacting Chromium in container...
Docker Chromium: Attempt #2
Docker Chromium: Attempt #3
Docker Chromium: Attempt #4
Docker Chromium: Attempt #5
Docker Chromium: Max number of attempts exceeded. I'm giving up!
(node:124) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 127.0.0.1:9222
    at new RequestError (/home/circleci/project/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/circleci/project/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/circleci/project/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/circleci/project/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/home/circleci/project/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
(node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 42.06s.
```

- Somehow the container seems to start, but the script can't reach chrome. 
- What's even weirder: in this case the tests don't fail but pass, leading to a green ci result although clearly the tests should have failed.

So my question boils down to: How can I debug this better? The stack trace doesn't look to helpful here.

**Comment by gidztech** [comment]
Thanks for reporting this. I'll try to take a look at this when I get some time today. Interestingly, I didn't have this problem on TravisCI (used for CI in this project) and with TeamCity at work. I'll see if I can reproduce this on a separate project with CircleCI and go from there.

**Comment by gidztech** [comment]
I worked out why the tests were failing. It turns out that CircleCI base Docker containers are not accessible from remote Docker containers - they're on different environments.

To get around this, I found that if the `machine` executor is used instead of Docker, we are able to launch a container on the same environment.

I've added a [Troubleshooting](https://github.com/gidztech/jest-puppeteer-docker#circleci) section on the README with more details, but you can see an [example CircleCI config](https://github.com/gidztech/jest-puppeteer-docker/blob/master/example/ci/.circleci/config.yml) that should work. I'd like to find a better solution for this though.
