### ISSUE TITLE
Use setupFilesAfterEnv instead of deprecated setupTestFrameworkScriptFile

### ISSUE THREAD

**Issue by test-pilott** [gidztech/jest-puppeteer-docker#21]
Hey, 

With the latest version of `jest-puppeteer` (3.9.0+) there is this following issue if a project uses a mix of `setupFilesAfterEnv` and `setupTestFrameworkScriptFile` config: 

`Options: setupTestFrameworkScriptFile and setupFilesAfterEnv cannot be used together.
  Please change your configuration to only use setupFilesAfterEnv.`

`setupTestFrameworkScriptFile` will be deprecated. 

I would guess the solution is to simply change this file https://github.com/gidztech/jest-puppeteer-docker/blob/master/jest-preset.js to use `setupFilesAfterEnv` instead. 

Note: according to the specs `setupFilesAfterEnv` accepts an array instead of a string https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

Dependencies: 
"jest": "24.4.0"
"jest-puppeteer": "4.0.0"
"jest-image-snapshot": "2.8.1"
"jest-component-snapshot": "0.1.2"
"jest-puppeteer-docker": "1.1.3"

Thanks!

**Comment by gidztech** [comment]
Thanks for raising the issue. I've updated the minimum dependencies and we're now using `setupFilesAfterEnv`. Hopefully this should solve the problem.

**Comment by test-pilott** [comment]
Thanks, it works well now with 1.2.0.
