### ISSUE TITLE
How can I use my own docker container (either local or from Artifactory)?

### ISSUE THREAD

**Issue by icfantv** [gidztech/jest-puppeteer-docker#23]
Hi, I saw [this commit](https://github.com/gidztech/jest-puppeteer-docker/commit/58261a0bcc4a490cfd8cd7259cb2a25fdcfa5897) and am thinking it's addressing the issue I want, but my docker-fu is weak.

Our CI system is locked down in that it cannot connect to the Internet, so I built my own container following the instructions [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker).  So all I think I need now, is to be able to tell jest-puppeteer-docker to use my container (either locally installed, or pull from our locked-down artifactory server) instead.  How can I do this?  Thanks.

The onus would be on me to make sure the versions of my project match the puppeteer version I installed on the container - but I'm ok with that.

**Comment by icfantv** [comment]
Actually, the more I think about this, I don't actually need puppeteer running in a container, rather, I just need chrome, which we have.  The advantage of installing puppeteer on the container is ensuring that the right/paired version of chromium for that version of puppeteer is downloaded for us.  In this instance, the versions of puppeteer between the container and the project would need to match.

**Comment by gidztech** [comment]
If I understand correctly, you'd like to be able to reference your own Dockerfile to build the Chromium container? I think it should be possible to update `docker-chromium` to take in a reference to a Dockerfile and build the container from that. That should be relatively straightforward.

I think the only complexity is around the version of Chromium used. This library will patch the internal Dockerfile to update the Chromium revision number to match your Puppeteer version. Either the new mode for using a custom Dockerfile ignores this and just hope your version is compatible, or we need to agree on a format for the Dockerfile where we can patch the version. Right now, I look for `REV=` prefix, and that is a variable that constructs the URI to download Chromium.

**Comment by icfantv** [comment]
@gidztech hey, I was able to get this working nicely running chrome in a container and having a local puppeteer connect to it.  We're also able to push the container image up to our dev artifactory so it can work in CI.  Thanks.
