### ISSUE TITLE
Having trouble getting headless: true, dumpio: true, and page.evaluate to work

### ISSUE THREAD

**Issue by wickkidd** [gidztech/jest-puppeteer-docker#24]
I'm adding jest-puppeteer-docker to an existing repo where headless: true, dumpio: true, and page.evaluate all work correctly. Tests do execute against the docker container now, but neither of those config settings work and the code I have inside of a page.evaluate isn't executing correctly (or perhaps not in the correct runtime or something like that). My page.evaluate code simply grabs some elements and reads, then parses the computed css and returns specific values from it. Here's my jest-puppeteer.config.js

```javascript
const baseConfig = require('jest-puppeteer-docker/lib/config')()
const config = Object.assign({}, baseConfig)

// Config options https://github.com/smooth-code/jest-puppeteer/tree/v4.3.0/packages/jest-environment-puppeteer#jest-puppeteerconfigjs
config.launch = {
	dumpio: true, // outputs chromedriver log to node's log (local)
	headless: false, // false if you want to see the browser open (helps for debugging)
	slowMo: 0
}

module.exports = config
```

My first thought would be some sort of configuration mistake on my part. Any ideas?

**Comment by wickkidd** [comment]
### Headless (false)
Still haven't gotten that to work.

### Logging
I finally [found a way](https://stackoverflow.com/a/46245945/260279) to get the logging to pass through to the node process log although `dumpio: true` still seems to have no effect.

Here's how I implemented it (`PUPPETEER_PAGE_LOG` is simply something I added to toggle it on and off):
```javascript
if (process.env.PUPPETEER_PAGE_LOG) page.on('console', msg => console.log('page log:', msg.text()))
```
which is in a file that is passed to `setupFilesAfterEnv` in jest config.

### page.evaluate
That actually was working, but until I was able to get the logging to pass through to the node process, I wasn't able to verify it. Once I was, I found that chromium has a problem with `array1.push.apply(array2, array3)` where it doesn't modify `array1`. I ended up refactoring to `array1 = [...array2, ...array3]` and all was good.

### Thoughts
While I'm no longer blocked on getting my repo's puppeteer tests working with chromium in docker, it would be nice if I could get `dumpio: true` and `headless: false` to work. If anyone figures either out, please post a reply.

Also, @gidztech thanks for sharing this module. It worked right the first time and aside from not being able to get dumpio and headless working, it was painless to get going. 👍

**Comment by gidztech** [comment]
Hey @wickkidd. Sorry for the late reply, I missed this. I will try to make some time to look into this over the weekend and get back to you.

**Comment by gidztech** [comment]
The issue here is that we are launching Chromium ourselves in the Docker's entrypoint shell script instead of via Puppeteer's API, so the `launch` properties don't get applied.

We can pass Chromium flags instead in the `jest-puppeter.config.js` file like:

```js
customConfig.chromiumFlags = ['--headless=false', '–ignore-certificate-errors'];
```

However, because there's no hardware display in a Docker container, this would fail to launch. I'm looking at updating the Dockerfile to bring in `Xvfb` as a virtual display and `x11vnc` server to allow us to VNC into the container and view the browser display. I played around with it but not managed to get it working just yet. There's added complexity around pausing the test running so you can run your local VNC client before the container shuts down. 

https://en.wikipedia.org/wiki/Xvfb#Remote_control_over_SSH

**Comment by wickkidd** [comment]
Thanks for explaining why the launch options don't work (and for explaining the alternative). 

I kinda figured that was the case regarding video output (`headless: false`). If you're running linux then you can simply run the tests without jest-puppeteer-docker and be fairly assured that you're getting the same result, but for those (many) of us on a mac (or other platforms) that will be more difficult. I keep an old decommissioned laptop running linux around exactly for situations like this.

I'll close the issue since you addressed the issue and we have a workaround for the things that are possible. You can always reopen or reference this issue if/when you get video output working.
