### ISSUE TITLE
This seems to be not working at all

### ISSUE THREAD

**Issue by cursedcoder** [gidztech/jest-puppeteer-docker#27]
![image](https://user-images.githubusercontent.com/899452/69416911-5d151a00-0d20-11ea-933c-e8d68b44018c.png)

Even local example uses the OS puppeeter, not docker's one.

**Comment by gidztech** [comment]
I've not seen this before but I was having issues with the container today due to Ubuntu 14.04 LTS transitioning to ESM - which resulted in fetches from the amplitude repository failing with 401s. I've now upraded it to 18.04 LTS.

Could you try again and see if version 1.3.0 resolves this? @cursedcoder

**Comment by cursedcoder** [comment]
I'm pretty sure this is not related to Ubuntu in any way.

I dropped jest-puppeteer-docker and instead used your docker-chromium@1.0.0 with a simple config file:

```
# jest.integration.config
module.exports = {
  globalSetup: 'jest-environment-puppeteer/setup',
  globalTeardown: './config/docker-teardown',
  testEnvironment: 'jest-environment-puppeteer',
  testMatch: [`<rootDir>/components/**/*.itest.js`],
  setupFilesAfterEnv: ['./config/setup-tests.js'],
  setupFiles: ['./node_modules/regenerator-runtime/runtime'],
};
```

```
# config/docker-teardown.js
const {
  dockerShutdownChromium,
} = require('docker-chromium'); // eslint-disable-line

module.exports = dockerShutdownChromium;
```

```
# jest-puppeteer.config.js
require('@babel/polyfill');

const {
  dockerSetChromiumConfig,
  dockerRunChromium,
} = require('docker-chromium');

async function getConfig() {
  await dockerSetChromiumConfig({
    revision: '646161',
    flags: ['-–ignore-certificate-errors', '--hide-scrollbars'],
  });
  const browserWSEndpoint = await dockerRunChromium();

  return {
    connect: {
      browserWSEndpoint,
    },
  };
}

module.exports = getConfig();
```

Works as expected.
