### ISSUE TITLE
Fails to run on Jenkins 

### ISSUE THREAD

**Issue by frosemond** [gidztech/jest-puppeteer-docker#34]
When using this in a Jenkins build environment I am getting the following error.  From my reading, this is due to missing dependencies in the Docker container.

`Failed to launch the browser process!
10:01:27      /home/jenkins/agent/workspace/tools_cbdc-e2e-testing_master/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
10:01:27  
10:01:27  
10:01:27      TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
10:01:27  
10:01:27        at onClose (node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
10:01:27        at Interface.<anonymous> (node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)`

**Comment by gidztech** [comment]
@frosemond  I've not had this issue on other environments but I've added `libxss1` dependency to the Dockerfile now, and released a new version. Let me know if that resolves the issue for you.
